---
apiVersion: v1
kind: Secret
metadata:
  name: netrc
  namespace: default
type: Opaque
stringData:
  .netrc: |
    machine github.com login $GITHUB_USERNAME password $GITHUB_TOKEN
    machine raw.githubusercontent.com login $GITHUB_USERNAME password $GITHUB_TOKEN