---
apiVersion: v1
kind: Service
metadata:
  name: gman
  namespace: default
  labels:
    app: gman
spec:
  type: ClusterIP
  selector:
    app: gman
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http